Fiszki/urls.py
from django.conf.urls import include, url
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Examples:
    # url(r'^$', 'Fiszki.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', RedirectView.as_view(url='dashboard/', permanent=False)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('dashboard.urls', namespace="dashboard"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.conf.urls import url
from dashboard.views import *

app_name = 'dashboard'

urlpatterns = [

    # /dashboard/
    url(r'^$', Dashboard.as_view(), name='dashboard'),

    # /dashboard/register
    url(r'^register/$', UserFormView.as_view(), name='register'),

    # /dashboard/add_word/
    url(r'^add_word/$', Add_word.as_view(), name='add_word'),

    # /dashboard/add_word/add
    url(r'^(?P<pk>[0-9]+)/$', DictionaryDetail.as_view(), name='dict'),

    # /dashboard/add/
    url(r'dict/add/$', DictionaryCreate.as_view(), name='dict_add'),

    # /dashboard/2/update/
    url(r'dict/(?P<pk>[0-9]+)/$', DictionaryUpdate.as_view(), name='dict_update'),

    # /dashboard/2/delete/
    url(r'dict/(?P<pk>[0-9]+)/delete/$', DictionaryDelete.as_view(), name='dict_del')
]

accounts/models.py
from django.db import models

# Create your models here.

dashboard/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Dictionary(models.Model):
    title = models.CharField(max_length=100)
    logo = models.FileField(null=True)

    def get_absolute_url(self):
        return reverse('dashboard:dict', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

class Word(models.Model):
    dictionary = models.ForeignKey(Dictionary, on_delete=models.CASCADE, null=True)
    english = models.CharField(max_length=50)
    polish = models.CharField(max_length=100)


    def __str__(self):
        return self.english + " - " + self.polish

dashboard/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import authenticate, login
from dashboard.forms import UserForm

# Create your views here.
# class UserFormView(View):
#     form_class = UserForm
#     template_name = 'dashboard/registration_form.html'
#
#     def get(self, request):
#         form = self.form_class(None)
#         return render(request, self.template_name, {'form': form})
#
#     def post(self, request):
#         form = self.form_class(request.POST)
#
#         if form.is_valid():
#             user = form.save(commit=False)
#
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#
#             #change pass:
#             # user.set_password(password)
#
#             user.save()
#
#             user = authenticate(username=username, password=password)

        #     if user is not None:
        #         if user.is_active:
        #             login(request, user)
        #             return redirect('dashboard:dashboard')
        #
        # return render(request, self.template_name, {'form': form})

dashboard/views.py
from django.shortcuts import render, redirect
from dashboard.models import Word
from dashboard.models import Dictionary as DictionaryModel
from django.views.generic import View, ListView, CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login
from dashboard.forms import UserForm
# import datetime

class Dashboard(ListView):
    template_name = 'dashboard/home.html'
    context_object_name = 'all_dicts'

    def get_queryset(self):
        return DictionaryModel.objects.all()


class Add_word(View):
    def get(self, request):
        return render(request, 'dashboard/add_words.html')

    def post(self, request):
        en = request.POST.get('en_word', "")
        pl = request.POST.get('pl_word', "")

        try:
            word = Word.objects.get(english=en)

            msg = "Słówko: '" + str(en) + "' jest już w bazie."
            return render(request, 'dashboard/add_words.html', {'err_message': msg})

        except ObjectDoesNotExist:
            Word.objects.create(english=en, polish=pl)
            msg = "Słówko: '" + str(en) + "' zostało dodane."
            return render(request, 'dashboard/add_words.html', {'suc_message': msg})

        # now = datetime.datetime.now()
        # html = "<html><body>It is now %s.</body></html>" % now
        # return HttpResponse(html)


class AddWord(CreateView):
    object = Word
    fields = ['english', 'polish']


class DictionaryCreate(CreateView):
    model = DictionaryModel
    fields = ['title','logo']


class DictionaryDetail(DetailView):
    template_name = 'dashboard/dictionary.html'
    model = DictionaryModel

    def get_context_data(self, **kwargs):
        context = super(DictionaryDetail, self).get_context_data(**kwargs)
        context['words'] = Word.objects.all()
        zawartosc = ""
        for c in context:
            zawartosc = zawartosc + str(c)
        context['title'] = zawartosc
        return context


class DictionaryDelete(DeleteView):
    model = DictionaryModel
    success_url = reverse_lazy('dashboard:dashboard')


class DictionaryUpdate(UpdateView):
    model = DictionaryModel
    fields = ['title']

class UserFormView(View):
    form_class = UserForm
    template_name = 'dashboard/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            #change pass:
            # user.set_password(password)

            user.save()

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('dashboard:dashboard')

        return render(request, self.template_name, {'form': form})

dashboard/templates/add_words.html
{% extends 'base.html' %}

{% block view_content %}
    <div class="workspace col-lg-12">
        <div class="text-center">
            <h1>Dodaj słówka</h1>
        </div>

        <div class="col-lg-12">
                {% if err_message %}
                    <div class="alert alert-warning" role="alert">
                        <strong>Uwaga!</strong>{{ err_message }}
                    </div>
                {%  endif %}

                {% if suc_message %}
                    <div class="alert alert-success" role="alert">
                        <strong>Sukces!</strong>{{ suc_message }}
                    </div>
                {%  endif %}
        </div>

        <div>
            <form method="POST" action="{% url 'add_word' %}">
            {% csrf_token %}

                <div class="col-lg-4 col-lg-offset-2">
                    <div class="col-lg-1">
                        <a> <img src="/static/en.ico" alt="en_icon" height="12" width="12"> </a>
                    </div>
                    <div class="col-lg-11">
                        <input name="en_word" id="id_en_word"
                            class="form-control input-group-sm"
                            placeholder="Słówko [eng]" />
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="col-lg-11">
                        <input name="pl_word" id="id_pl_word"
                            class="form-control input-group-sm"
                            placeholder="Tłumaczenie [pl]" />
                    </div>
                    <div class="col-lg-1">
                        <a> <img src="/static/pl.ico" alt="pl_icon" height="12" width="12"> </a>
                    </div>
                </div>
                <div class="col-lg-2">
                    <input type="submit" value="Dodaj">
                </div>


            </form>
        </div>
    </div>
{% endblock %}

dashboard/templates/base.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <title>Fiszki</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/static/bootstrap/css/simple-sidebar.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>

	<body>

        <div class="container-fluid">

            <div class="row">
			    <div class="dashboard_bar">
				    <p class="dashboard_bar"><span>F</span>iszki</p>
			    </div>
		    </div><!--/.row-->
        </div>


        <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="{% url 'dashboard' %}">
                        Menu
                    </a>
                </li>
                <li>
                    <a href="{% url 'add_word' %}">Dodaj słówka</a>
                </li>
                <li>
                    <a href="{% url 'dictionary' %}">Słownik</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper container-fluid">
                <div class="row">
                    <div class="path_bar col-lg-12">
                        <a href="{% url 'dashboard' %}"> <img src="/static/home.png" alt="home_icon" height="12" width="12"> / </a>
                    </div>

                    {% block view_content %}

                    {% endblock %}

                    <div class="col-lg-12">
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>

                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/static/bootstrap/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

	</body>
</html>

dashboard/templates/dashboard/add_words.html
{% extends 'dashboard/base.html' %}

{% block view_content %}
    <div class="workspace col-lg-12">
        <div class="text-center">
            <h1>Dodaj słówka</h1>
        </div>

        <div class="col-lg-12">
                {% if err_message %}
                    <div class="alert alert-warning" role="alert">
                        <strong>Uwaga!</strong>{{ err_message }}
                    </div>
                {%  endif %}

                {% if suc_message %}
                    <div class="alert alert-success" role="alert">
                        <strong>Sukces!</strong>{{ suc_message }}
                    </div>
                {%  endif %}
        </div>

        <div>
            <form method="POST" action="{% url 'dashboard:add_word' %}">
            {% csrf_token %}

                <div class="col-lg-4 col-lg-offset-2">
                    <div class="col-lg-1">
                        <a> <img src="/static/en.ico" alt="en_icon" height="12" width="12"> </a>
                    </div>
                    <div class="col-lg-11">
                        <input name="en_word" id="id_en_word"
                            class="form-control input-group-sm"
                            placeholder="Słówko [eng]" />
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="col-lg-11">
                        <input name="pl_word" id="id_pl_word"
                            class="form-control input-group-sm"
                            placeholder="Tłumaczenie [pl]" />
                    </div>
                    <div class="col-lg-1">
                        <a> <img src="/static/pl.ico" alt="pl_icon" height="12" width="12"> </a>
                    </div>
                </div>
                <div class="col-lg-2">
                    <input type="submit" value="Dodaj">
                </div>


            </form>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <title>Fiszki</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/static/bootstrap/css/simple-sidebar.css" rel="stylesheet">
        <link href="/static/base.css" rel="stylesheet">
    </head>

	<body>

        <div class="container-fluid">

            <div class="row">
			    <div class="dashboard_bar">
				    <p class="dashboard_bar"><span>F</span>iszki</p>
			    </div>
		    </div><!--/.row-->
        </div>


        <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="{% url 'dashboard:dashboard' %}">
                        Menu
                    </a>
                </li>
                <li>
                    <a href="{% url 'dashboard:add_word' %}">Dodaj słówka</a>
                </li>
                <li>
                    <a href="{% url 'dashboard:dict_add' %}">Dodaj słownik</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper container-fluid">
                <div class="row">
                    <div class="path_bar col-lg-12">
                        <a href="{% url 'dashboard:dashboard' %}"> <img src="/static/home.png" alt="home_icon" height="12" width="12"> / </a>
                    </div>

                    {% block view_content %}

                    {% endblock %}

                    <div class="col-lg-12">
                        <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>
                    </div>

                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/static/bootstrap/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

	</body>
</html>

dashboard/templates/dashboard/dictionary.html
{% extends 'dashboard/base.html' %}

{% block view_content %}
    <div class="workspace col-lg-12">
        <div class="text-center">
            <h1>Słownik</h1>
        </div>
    </div>

    <div class="col-lg-3">
        <div class="img-thumbnail">
         <img src="{{ dictionary.logo.url }}" alt="lorem_pixel" width="300" height="300">
            <div class="caption">
                <h2>{{ dictionary.title }}</h2>
                <h4>Opis...</h4>
            </div>
        </div>
    </div>

    <style>
        .table-hover > tbody tr:hover > td,
        .table-hover > tbody tr:hover > th {
            background-color: salmon;
        }
    </style>
        <div class="col-lg-6">
            <table id="id_list_table" class="table table-hover table-striped table-condensed">

                {% for word in words %}
                    <tr>
                        <td>{{ forloop.counter }}: {{ word }}</td>
                    </tr>
                {% endfor %}

            </table>
        </div>

{% endblock %}

dashboard/templates/dashboard/dictionary_form.html
{% extends 'dashboard/base.html' %}
{% block view_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {%  include 'dashboard/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dashboard/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">
            {{ field.label_tag }}
        </label>
        <div class="col-sm-10">
            {{ field }}
        </div>
    </div>

{% endfor %}

dashboard/templates/dashboard/home.html
{% extends 'dashboard/base.html' %}

{% block view_content %}
    <div class="workspace col-lg-12 jumbotron">
        <div class="text-center">
            <h1>Witaj!</h1>
        </div>
        <div class="text-left">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce semper tellus est, non rhoncus odio
                condimentum non. Praesent mollis leo arcu, eget interdum ipsum tristique ornare. Aenean malesuada
                sagittis molestie. Nulla congue erat in orci consectetur, sit amet volutpat nunc consectetur. Quisque
                vel nisi gravida, interdum leo at, aliquam mi. Praesent condimentum finibus leo, a commodo metus
                accumsan facilisis. Pellentesque sit amet magna sed tortor bibendum vehicula a ac massa.
                Integer malesuada, massa et lacinia dictum, tellus dui mattis erat, sed pulvinar justo nibh nec lorem.
            </p>
        </div>
    </div>
    <ul>
        {% for dict in all_dicts %}
            <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'dashboard:dict' dict.id %}">
                            <img src="{{ dictionary.logo.url }}" alt="lorem_pixel" width="200" height="200">
                        </a>
                        <div class="caption">
                            <h2>{{ dict.title }}</h2>
                            <h4>Opis...</h4>

                            <a href="{% url 'dashboard:dict_update' dict.id %}" class="btn btn-default btn-sm" role="button">
                                <span class="glyphicon glyphicon-edit active"></span>
{#                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>#}
                            </a>
                            <form action="{% url 'dashboard:dict_del' dict.id %}" method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="dict_id" value="{{ dict.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                        </div>
                    </div>
            </div>
        {% endfor %}
    </ul>
{% endblock %}

dashboard/templates/dashboard/registration_form.html
{% extends 'dashboard/base.html' %}
{% block view_content %}
    <div class="container-fluid">
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h2>Create a new Account</h2>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {%  include 'dashboard/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

dashboard/templates/dictionary.html
{% extends 'base.html' %}

{% block view_content %}
    <div class="workspace col-lg-12">
        <div class="text-center">
            <h1>Słownik</h1>
        </div>
    </div>

    <style>
        .table-hover > tbody tr:hover > td,
        .table-hover > tbody tr:hover > th {
            background-color: salmon;
        }
    </style>
{#    <div class="row">#}
        <div class="col-lg-6 col-lg-offset-3">
            <table id="id_list_table" class="table table-hover table-striped table-condensed">

                {% for word in words %}
                    <tr>
                        <td>{{ forloop.counter }}: {{ word }}</td>
                    </tr>
                {% endfor %}

            </table>
        </div>
{#    </div>#}

{% endblock %}